import '../models/currency.dart';
import 'constants.dart';

/// Chinese display names for every currency returned by open.er-api.com
/// (ISO 4217, ~161 codes). Symbols are provided where they are widely
/// recognized; otherwise the code itself is used as a neutral fallback.
///
/// [currencyOf] resolves any code — unknown codes degrade to a code-only
/// entry so the app never crashes on a currency the map does not list.
const Map<String, Currency> kCurrencyMeta = {
  'AED': Currency(code: 'AED', cnName: '阿联酋迪拉姆', enName: 'UAE Dirham', jaName: 'UAEディルハム', symbol: 'د.إ'),
  'AFN': Currency(code: 'AFN', cnName: '阿富汗尼', enName: 'Afghan Afghani', jaName: 'アフガニ', symbol: '؋'),
  'ALL': Currency(code: 'ALL', cnName: '阿尔巴尼亚列克', enName: 'Albanian Lek', jaName: 'アルバニアレク', symbol: 'L'),
  'AMD': Currency(code: 'AMD', cnName: '亚美尼亚德拉姆', enName: 'Armenian Dram', jaName: 'アルメニアドラム', symbol: '֏'),
  'ANG': Currency(code: 'ANG', cnName: '荷属安的列斯盾', enName: 'Netherlands Antillean Guilder', jaName: 'オランダ領アンティルギルダー', symbol: 'ƒ'),
  'AOA': Currency(code: 'AOA', cnName: '安哥拉宽扎', enName: 'Angolan Kwanza', jaName: 'アンゴラクワンザ', symbol: 'Kz'),
  'ARS': Currency(code: 'ARS', cnName: '阿根廷比索', enName: 'Argentine Peso', jaName: 'アルゼンチンペソ', symbol: '\$'),
  'AUD': Currency(code: 'AUD', cnName: '澳大利亚元', enName: 'Australian Dollar', jaName: '豪ドル', symbol: '\$'),
  'AWG': Currency(code: 'AWG', cnName: '阿鲁巴弗罗林', enName: 'Aruban Florin', jaName: 'アルバフロリン', symbol: 'ƒ'),
  'AZN': Currency(code: 'AZN', cnName: '阿塞拜疆马纳特', enName: 'Azerbaijani Manat', jaName: 'アゼルバイジャンマナト', symbol: '₼'),
  'BAM': Currency(code: 'BAM', cnName: '波黑可兑换马克', enName: 'Bosnia-Herzegovina Convertible Mark', jaName: 'ボスニア・ヘルツェゴビナ兌換マルク', symbol: 'KM'),
  'BBD': Currency(code: 'BBD', cnName: '巴巴多斯元', enName: 'Barbadian Dollar', jaName: 'バルバドスドル', symbol: '\$'),
  'BDT': Currency(code: 'BDT', cnName: '孟加拉塔卡', enName: 'Bangladeshi Taka', jaName: 'バングラデシュタカ', symbol: '৳'),
  'BGN': Currency(code: 'BGN', cnName: '保加利亚列弗', enName: 'Bulgarian Lev', jaName: 'ブルガリアレフ', symbol: 'лв'),
  'BHD': Currency(code: 'BHD', cnName: '巴林第纳尔', enName: 'Bahraini Dinar', jaName: 'バーレーンディナール', symbol: '.د.ب'),
  'BIF': Currency(code: 'BIF', cnName: '布隆迪法郎', enName: 'Burundian Franc', jaName: 'ブルンジフラン', symbol: 'FBu'),
  'BMD': Currency(code: 'BMD', cnName: '百慕大元', enName: 'Bermudian Dollar', jaName: 'バミューダドル', symbol: '\$'),
  'BND': Currency(code: 'BND', cnName: '文莱元', enName: 'Brunei Dollar', jaName: 'ブルネイドル', symbol: '\$'),
  'BOB': Currency(code: 'BOB', cnName: '玻利维亚诺', enName: 'Bolivian Boliviano', jaName: 'ボリビアーノ', symbol: 'Bs.'),
  'BRL': Currency(code: 'BRL', cnName: '巴西雷亚尔', enName: 'Brazilian Real', jaName: 'ブラジルレアル', symbol: 'R\$'),
  'BSD': Currency(code: 'BSD', cnName: '巴哈马元', enName: 'Bahamian Dollar', jaName: 'バハマドル', symbol: '\$'),
  'BTN': Currency(code: 'BTN', cnName: '不丹努尔特鲁姆', enName: 'Bhutanese Ngultrum', jaName: 'ブータンニュルタム', symbol: 'Nu.'),
  'BWP': Currency(code: 'BWP', cnName: '博茨瓦纳普拉', enName: 'Botswana Pula', jaName: 'ボツワナプラ', symbol: 'P'),
  'BYN': Currency(code: 'BYN', cnName: '白俄罗斯卢布', enName: 'Belarusian Ruble', jaName: 'ベラルーシルーブル', symbol: 'Br'),
  'BZD': Currency(code: 'BZD', cnName: '伯利兹元', enName: 'Belize Dollar', jaName: 'ベリーズドル', symbol: '\$'),
  'CAD': Currency(code: 'CAD', cnName: '加拿大元', enName: 'Canadian Dollar', jaName: 'カナダドル', symbol: '\$'),
  'CDF': Currency(code: 'CDF', cnName: '刚果法郎', enName: 'Congolese Franc', jaName: 'コンゴフラン', symbol: 'FC'),
  'CHF': Currency(code: 'CHF', cnName: '瑞士法郎', enName: 'Swiss Franc', jaName: 'スイスフラン', symbol: 'Fr'),
  'CLP': Currency(code: 'CLP', cnName: '智利比索', enName: 'Chilean Peso', jaName: 'チリペソ', symbol: '\$'),
  'CNY': Currency(code: 'CNY', cnName: '人民币', enName: 'Chinese Yuan', jaName: '人民元', symbol: '¥'),
  'COP': Currency(code: 'COP', cnName: '哥伦比亚比索', enName: 'Colombian Peso', jaName: 'コロンビアペソ', symbol: '\$'),
  'CRC': Currency(code: 'CRC', cnName: '哥斯达黎加科朗', enName: 'Costa Rican Colón', jaName: 'コスタリカコロン', symbol: '₡'),
  'CUP': Currency(code: 'CUP', cnName: '古巴比索', enName: 'Cuban Peso', jaName: 'キューバペソ', symbol: '\$'),
  'CVE': Currency(code: 'CVE', cnName: '佛得角埃斯库多', enName: 'Cape Verdean Escudo', jaName: 'カーボベルデエスクード', symbol: '\$'),
  'CZK': Currency(code: 'CZK', cnName: '捷克克朗', enName: 'Czech Koruna', jaName: 'チェココルナ', symbol: 'Kč'),
  'DJF': Currency(code: 'DJF', cnName: '吉布提法郎', enName: 'Djiboutian Franc', jaName: 'ジブチフラン', symbol: 'Fdj'),
  'DKK': Currency(code: 'DKK', cnName: '丹麦克朗', enName: 'Danish Krone', jaName: 'デンマーククローネ', symbol: 'kr'),
  'DOP': Currency(code: 'DOP', cnName: '多米尼加比索', enName: 'Dominican Peso', jaName: 'ドミニカペソ', symbol: 'RD\$'),
  'DZD': Currency(code: 'DZD', cnName: '阿尔及利亚第纳尔', enName: 'Algerian Dinar', jaName: 'アルジェリアディナール', symbol: 'دج'),
  'EGP': Currency(code: 'EGP', cnName: '埃及镑', enName: 'Egyptian Pound', jaName: 'エジプトポンド', symbol: '£'),
  'ERN': Currency(code: 'ERN', cnName: '厄立特里亚纳克法', enName: 'Eritrean Nakfa', jaName: 'エリトリアナクファ', symbol: 'Nfk'),
  'ETB': Currency(code: 'ETB', cnName: '埃塞俄比亚比尔', enName: 'Ethiopian Birr', jaName: 'エチオピアブル', symbol: 'Br'),
  'EUR': Currency(code: 'EUR', cnName: '欧元', enName: 'Euro', jaName: 'ユーロ', symbol: '€'),
  'FJD': Currency(code: 'FJD', cnName: '斐济元', enName: 'Fijian Dollar', jaName: 'フィジードル', symbol: '\$'),
  'FKP': Currency(code: 'FKP', cnName: '福克兰群岛镑', enName: 'Falkland Islands Pound', jaName: 'フォークランド諸島ポンド', symbol: '£'),
  'FOK': Currency(code: 'FOK', cnName: '法罗群岛克朗', enName: 'Faroese Króna', jaName: 'フェロー諸島クローネ', symbol: 'kr'),
  'GBP': Currency(code: 'GBP', cnName: '英镑', enName: 'British Pound', jaName: '英ポンド', symbol: '£'),
  'GEL': Currency(code: 'GEL', cnName: '格鲁吉亚拉里', enName: 'Georgian Lari', jaName: 'ジョージアラリ', symbol: '₾'),
  'GGP': Currency(code: 'GGP', cnName: '根西镑', enName: 'Guernsey Pound', jaName: 'ガーンジーポンド', symbol: '£'),
  'GHS': Currency(code: 'GHS', cnName: '加纳塞地', enName: 'Ghanaian Cedi', jaName: 'ガーナセディ', symbol: '₵'),
  'GIP': Currency(code: 'GIP', cnName: '直布罗陀镑', enName: 'Gibraltar Pound', jaName: 'ジブラルタルポンド', symbol: '£'),
  'GMD': Currency(code: 'GMD', cnName: '冈比亚达拉西', enName: 'Gambian Dalasi', jaName: 'ガンビアダラシ', symbol: 'D'),
  'GNF': Currency(code: 'GNF', cnName: '几内亚法郎', enName: 'Guinean Franc', jaName: 'ギニアフラン', symbol: 'FG'),
  'GTQ': Currency(code: 'GTQ', cnName: '危地马拉格查尔', enName: 'Guatemalan Quetzal', jaName: 'グアテマラケツァル', symbol: 'Q'),
  'GYD': Currency(code: 'GYD', cnName: '圭亚那元', enName: 'Guyanaese Dollar', jaName: 'ガイアナドル', symbol: '\$'),
  'HKD': Currency(code: 'HKD', cnName: '港币', enName: 'Hong Kong Dollar', jaName: '香港ドル', symbol: 'HK\$'),
  'HNL': Currency(code: 'HNL', cnName: '洪都拉斯伦皮拉', enName: 'Honduran Lempira', jaName: 'ホンジュラスレンピラ', symbol: 'L'),
  'HRK': Currency(code: 'HRK', cnName: '克罗地亚库纳', enName: 'Croatian Kuna', jaName: 'クロアチアクーナ', symbol: 'kn'),
  'HTG': Currency(code: 'HTG', cnName: '海地古德', enName: 'Haitian Gourde', jaName: 'ハイチグルド', symbol: 'G'),
  'HUF': Currency(code: 'HUF', cnName: '匈牙利福林', enName: 'Hungarian Forint', jaName: 'ハンガリーフォリント', symbol: 'Ft'),
  'IDR': Currency(code: 'IDR', cnName: '印度尼西亚盾', enName: 'Indonesian Rupiah', jaName: 'インドネシアルピア', symbol: 'Rp'),
  'ILS': Currency(code: 'ILS', cnName: '以色列新谢克尔', enName: 'Israeli New Shekel', jaName: 'イスラエル新シェケル', symbol: '₪'),
  'IMP': Currency(code: 'IMP', cnName: '马恩岛镑', enName: 'Isle of Man Pound', jaName: 'マン島ポンド', symbol: '£'),
  'INR': Currency(code: 'INR', cnName: '印度卢比', enName: 'Indian Rupee', jaName: 'インドルピー', symbol: '₹'),
  'IQD': Currency(code: 'IQD', cnName: '伊拉克第纳尔', enName: 'Iraqi Dinar', jaName: 'イラクディナール', symbol: 'ع.د'),
  'IRR': Currency(code: 'IRR', cnName: '伊朗里亚尔', enName: 'Iranian Rial', jaName: 'イランリアル', symbol: '﷼'),
  'ISK': Currency(code: 'ISK', cnName: '冰岛克朗', enName: 'Icelandic Króna', jaName: 'アイスランドクローナ', symbol: 'kr'),
  'JEP': Currency(code: 'JEP', cnName: '泽西镑', enName: 'Jersey Pound', jaName: 'ジャージーポンド', symbol: '£'),
  'JMD': Currency(code: 'JMD', cnName: '牙买加元', enName: 'Jamaican Dollar', jaName: 'ジャマイカドル', symbol: 'J\$'),
  'JOD': Currency(code: 'JOD', cnName: '约旦第纳尔', enName: 'Jordanian Dinar', jaName: 'ヨルダンディナール', symbol: 'د.ا'),
  'JPY': Currency(code: 'JPY', cnName: '日元', enName: 'Japanese Yen', jaName: '日本円', symbol: '¥'),
  'KES': Currency(code: 'KES', cnName: '肯尼亚先令', enName: 'Kenyan Shilling', jaName: 'ケニアシリング', symbol: 'KSh'),
  'KGS': Currency(code: 'KGS', cnName: '吉尔吉斯斯坦索姆', enName: 'Kyrgystani Som', jaName: 'キルギスソム', symbol: 'с'),
  'KHR': Currency(code: 'KHR', cnName: '柬埔寨瑞尔', enName: 'Cambodian Riel', jaName: 'カンボジアリエル', symbol: '៛'),
  'KID': Currency(code: 'KID', cnName: '基里巴斯元', enName: 'Kiribati Dollar', jaName: 'キリバスドル', symbol: '\$'),
  'KMF': Currency(code: 'KMF', cnName: '科摩罗法郎', enName: 'Comorian Franc', jaName: 'コモロフラン', symbol: 'CF'),
  'KRW': Currency(code: 'KRW', cnName: '韩元', enName: 'South Korean Won', jaName: '韓国ウォン', symbol: '₩'),
  'KWD': Currency(code: 'KWD', cnName: '科威特第纳尔', enName: 'Kuwaiti Dinar', jaName: 'クウェートディナール', symbol: 'د.ك'),
  'KYD': Currency(code: 'KYD', cnName: '开曼群岛元', enName: 'Cayman Islands Dollar', jaName: 'ケイマン諸島ドル', symbol: '\$'),
  'KZT': Currency(code: 'KZT', cnName: '哈萨克斯坦坚戈', enName: 'Kazakhstani Tenge', jaName: 'カザフスタンテンゲ', symbol: '₸'),
  'LAK': Currency(code: 'LAK', cnName: '老挝基普', enName: 'Laotian Kip', jaName: 'ラオスキープ', symbol: '₭'),
  'LBP': Currency(code: 'LBP', cnName: '黎巴嫩镑', enName: 'Lebanese Pound', jaName: 'レバノンポンド', symbol: 'ل.ل'),
  'LKR': Currency(code: 'LKR', cnName: '斯里兰卡卢比', enName: 'Sri Lankan Rupee', jaName: 'スリランカルピー', symbol: 'Rs'),
  'LRD': Currency(code: 'LRD', cnName: '利比里亚元', enName: 'Liberian Dollar', jaName: 'リベリアドル', symbol: '\$'),
  'LSL': Currency(code: 'LSL', cnName: '莱索托洛蒂', enName: 'Lesotho Loti', jaName: 'レソトロティ', symbol: 'L'),
  'LYD': Currency(code: 'LYD', cnName: '利比亚第纳尔', enName: 'Libyan Dinar', jaName: 'リビアディナール', symbol: 'ل.د'),
  'MAD': Currency(code: 'MAD', cnName: '摩洛哥迪拉姆', enName: 'Moroccan Dirham', jaName: 'モロッコディルハム', symbol: 'د.م.'),
  'MDL': Currency(code: 'MDL', cnName: '摩尔多瓦列伊', enName: 'Moldovan Leu', jaName: 'モルドバレウ', symbol: 'L'),
  'MGA': Currency(code: 'MGA', cnName: '马达加斯加阿里亚里', enName: 'Malagasy Ariary', jaName: 'マダガスカルアリアリ', symbol: 'Ar'),
  'MKD': Currency(code: 'MKD', cnName: '马其顿代纳尔', enName: 'Macedonian Denar', jaName: 'マケドニアデナール', symbol: 'ден'),
  'MMK': Currency(code: 'MMK', cnName: '缅甸元', enName: 'Myanmar Kyat', jaName: 'ミャンマーチャット', symbol: 'K'),
  'MNT': Currency(code: 'MNT', cnName: '蒙古图格里克', enName: 'Mongolian Tugrik', jaName: 'モンゴルトゥグルグ', symbol: '₮'),
  'MOP': Currency(code: 'MOP', cnName: '澳门元', enName: 'Macanese Pataca', jaName: 'マカオパタカ', symbol: 'MOP\$'),
  'MRU': Currency(code: 'MRU', cnName: '毛里塔尼亚乌吉亚', enName: 'Mauritanian Ouguiya', jaName: 'モーリタニアウギア', symbol: 'UM'),
  'MUR': Currency(code: 'MUR', cnName: '毛里求斯卢比', enName: 'Mauritian Rupee', jaName: 'モーリシャスルピー', symbol: 'Rs'),
  'MVR': Currency(code: 'MVR', cnName: '马尔代夫拉菲亚', enName: 'Maldivian Rufiyaa', jaName: 'モルディブルフィヤ', symbol: 'Rf'),
  'MWK': Currency(code: 'MWK', cnName: '马拉维克瓦查', enName: 'Malawian Kwacha', jaName: 'マラウイクワチャ', symbol: 'MK'),
  'MXN': Currency(code: 'MXN', cnName: '墨西哥比索', enName: 'Mexican Peso', jaName: 'メキシコペソ', symbol: '\$'),
  'MYR': Currency(code: 'MYR', cnName: '马来西亚林吉特', enName: 'Malaysian Ringgit', jaName: 'マレーシアリンギット', symbol: 'RM'),
  'MZN': Currency(code: 'MZN', cnName: '莫桑比克梅蒂卡尔', enName: 'Mozambican Metical', jaName: 'モザンビークメティカル', symbol: 'MT'),
  'NAD': Currency(code: 'NAD', cnName: '纳米比亚元', enName: 'Namibian Dollar', jaName: 'ナミビアドル', symbol: '\$'),
  'NGN': Currency(code: 'NGN', cnName: '尼日利亚奈拉', enName: 'Nigerian Naira', jaName: 'ナイジェリアナイラ', symbol: '₦'),
  'NIO': Currency(code: 'NIO', cnName: '尼加拉瓜科多巴', enName: 'Nicaraguan Córdoba', jaName: 'ニカラグアコルドバ', symbol: 'C\$'),
  'NOK': Currency(code: 'NOK', cnName: '挪威克朗', enName: 'Norwegian Krone', jaName: 'ノルウェークローネ', symbol: 'kr'),
  'NPR': Currency(code: 'NPR', cnName: '尼泊尔卢比', enName: 'Nepalese Rupee', jaName: 'ネパールルピー', symbol: 'Rs'),
  'NZD': Currency(code: 'NZD', cnName: '新西兰元', enName: 'New Zealand Dollar', jaName: 'ニュージーランドドル', symbol: '\$'),
  'OMR': Currency(code: 'OMR', cnName: '阿曼里亚尔', enName: 'Omani Rial', jaName: 'オマーンリアル', symbol: 'ر.ع.'),
  'PAB': Currency(code: 'PAB', cnName: '巴拿马巴波亚', enName: 'Panamanian Balboa', jaName: 'パナマバルボア', symbol: 'B/.'),
  'PEN': Currency(code: 'PEN', cnName: '秘鲁索尔', enName: 'Peruvian Sol', jaName: 'ペルーソル', symbol: 'S/.'),
  'PGK': Currency(code: 'PGK', cnName: '巴布亚新几内亚基那', enName: 'Papua New Guinean Kina', jaName: 'パプアニューギニアキナ', symbol: 'K'),
  'PHP': Currency(code: 'PHP', cnName: '菲律宾比索', enName: 'Philippine Peso', jaName: 'フィリピンペソ', symbol: '₱'),
  'PKR': Currency(code: 'PKR', cnName: '巴基斯坦卢比', enName: 'Pakistani Rupee', jaName: 'パキスタンルピー', symbol: 'Rs'),
  'PLN': Currency(code: 'PLN', cnName: '波兰兹罗提', enName: 'Polish Zloty', jaName: 'ポーランドズウォティ', symbol: 'zł'),
  'PYG': Currency(code: 'PYG', cnName: '巴拉圭瓜拉尼', enName: 'Paraguayan Guarani', jaName: 'パラグアイグアラニー', symbol: '₲'),
  'QAR': Currency(code: 'QAR', cnName: '卡塔尔里亚尔', enName: 'Qatari Rial', jaName: 'カタールリヤル', symbol: 'ر.ق'),
  'RON': Currency(code: 'RON', cnName: '罗马尼亚列伊', enName: 'Romanian Leu', jaName: 'ルーマニアレウ', symbol: 'lei'),
  'RSD': Currency(code: 'RSD', cnName: '塞尔维亚第纳尔', enName: 'Serbian Dinar', jaName: 'セルビアディナール', symbol: 'дин.'),
  'RUB': Currency(code: 'RUB', cnName: '俄罗斯卢布', enName: 'Russian Ruble', jaName: 'ロシアルーブル', symbol: '₽'),
  'RWF': Currency(code: 'RWF', cnName: '卢旺达法郎', enName: 'Rwandan Franc', jaName: 'ルワンダフラン', symbol: 'FRw'),
  'SAR': Currency(code: 'SAR', cnName: '沙特里亚尔', enName: 'Saudi Riyal', jaName: 'サウジアラビアリヤル', symbol: 'ر.س'),
  'SBD': Currency(code: 'SBD', cnName: '所罗门群岛元', enName: 'Solomon Islands Dollar', jaName: 'ソロモン諸島ドル', symbol: '\$'),
  'SCR': Currency(code: 'SCR', cnName: '塞舌尔卢比', enName: 'Seychellois Rupee', jaName: 'セーシェルルピー', symbol: 'Rs'),
  'SDG': Currency(code: 'SDG', cnName: '苏丹镑', enName: 'Sudanese Pound', jaName: 'スーダンポンド', symbol: 'ج.س.'),
  'SEK': Currency(code: 'SEK', cnName: '瑞典克朗', enName: 'Swedish Krona', jaName: 'スウェーデンクローナ', symbol: 'kr'),
  'SGD': Currency(code: 'SGD', cnName: '新加坡元', enName: 'Singapore Dollar', jaName: 'シンガポールドル', symbol: 'S\$'),
  'SHP': Currency(code: 'SHP', cnName: '圣赫勒拿镑', enName: 'Saint Helena Pound', jaName: 'セントヘレナポンド', symbol: '£'),
  'SLE': Currency(code: 'SLE', cnName: '塞拉利昂利昂', enName: 'Sierra Leonean Leone', jaName: 'シエラレオネレオン', symbol: 'Le'),
  'SOS': Currency(code: 'SOS', cnName: '索马里先令', enName: 'Somali Shilling', jaName: 'ソマリアシリング', symbol: 'Sh'),
  'SRD': Currency(code: 'SRD', cnName: '苏里南元', enName: 'Surinamese Dollar', jaName: 'スリナムドル', symbol: '\$'),
  'SSP': Currency(code: 'SSP', cnName: '南苏丹镑', enName: 'South Sudanese Pound', jaName: '南スーダンポンド', symbol: '£'),
  'STN': Currency(code: 'STN', cnName: '圣多美多布拉', enName: 'São Tomé and Príncipe Dobra', jaName: 'サントメ・プリンシペドブラ', symbol: 'Db'),
  'SYP': Currency(code: 'SYP', cnName: '叙利亚镑', enName: 'Syrian Pound', jaName: 'シリアポンド', symbol: '£'),
  'SZL': Currency(code: 'SZL', cnName: '斯威士兰里兰吉尼', enName: 'Swazi Lilangeni', jaName: 'スワジランドリランゲニ', symbol: 'L'),
  'THB': Currency(code: 'THB', cnName: '泰铢', enName: 'Thai Baht', jaName: 'タイバーツ', symbol: '฿'),
  'TJS': Currency(code: 'TJS', cnName: '塔吉克斯坦索莫尼', enName: 'Tajikistani Somoni', jaName: 'タジキスタンソモニ', symbol: 'ЅМ'),
  'TMT': Currency(code: 'TMT', cnName: '土库曼斯坦马纳特', enName: 'Turkmenistani Manat', jaName: 'トルクメニスタンマナト', symbol: 'm'),
  'TND': Currency(code: 'TND', cnName: '突尼斯第纳尔', enName: 'Tunisian Dinar', jaName: 'チュニジアディナール', symbol: 'د.ت'),
  'TOP': Currency(code: 'TOP', cnName: '汤加潘加', enName: 'Tongan Paʻanga', jaName: 'トンガパアンガ', symbol: 'T\$'),
  'TRY': Currency(code: 'TRY', cnName: '土耳其里拉', enName: 'Turkish Lira', jaName: 'トルコリラ', symbol: '₺'),
  'TTD': Currency(code: 'TTD', cnName: '特立尼达和多巴哥元', enName: 'Trinidad and Tobago Dollar', jaName: 'トリニダード・トバゴドル', symbol: 'TT\$'),
  'TVD': Currency(code: 'TVD', cnName: '图瓦卢元', enName: 'Tuvaluan Dollar', jaName: 'ツバルドル', symbol: '\$'),
  'TWD': Currency(code: 'TWD', cnName: '新台币', enName: 'New Taiwan Dollar', jaName: '新台湾ドル', symbol: 'NT\$'),
  'TZS': Currency(code: 'TZS', cnName: '坦桑尼亚先令', enName: 'Tanzanian Shilling', jaName: 'タンザニアシリング', symbol: 'TSh'),
  'UAH': Currency(code: 'UAH', cnName: '乌克兰格里夫纳', enName: 'Ukrainian Hryvnia', jaName: 'ウクライナフリヴニャ', symbol: '₴'),
  'UGX': Currency(code: 'UGX', cnName: '乌干达先令', enName: 'Ugandan Shilling', jaName: 'ウガンダシリング', symbol: 'USh'),
  'USD': Currency(code: 'USD', cnName: '美元', enName: 'US Dollar', jaName: '米ドル', symbol: '\$'),
  'UYU': Currency(code: 'UYU', cnName: '乌拉圭比索', enName: 'Uruguayan Peso', jaName: 'ウルグアイペソ', symbol: '\$U'),
  'UZS': Currency(code: 'UZS', cnName: '乌兹别克斯坦苏姆', enName: 'Uzbekistani Som', jaName: 'ウズベキスタンスム', symbol: "so'm"),
  'VES': Currency(code: 'VES', cnName: '委内瑞拉玻利瓦尔', enName: 'Venezuelan Bolívar', jaName: 'ベネズエラボリバル', symbol: 'Bs.'),
  'VND': Currency(code: 'VND', cnName: '越南盾', enName: 'Vietnamese Dong', jaName: 'ベトナムドン', symbol: '₫'),
  'VUV': Currency(code: 'VUV', cnName: '瓦努阿图瓦图', enName: 'Vanuatu Vatu', jaName: 'バヌアツバツ', symbol: 'VT'),
  'WST': Currency(code: 'WST', cnName: '萨摩亚塔拉', enName: 'Samoan Tala', jaName: 'サモアタラ', symbol: 'WS\$'),
  'XAF': Currency(code: 'XAF', cnName: '中非法郎', enName: 'Central African CFA Franc', jaName: '中央アフリカCFAフラン', symbol: 'FCFA'),
  'XCD': Currency(code: 'XCD', cnName: '东加勒比元', enName: 'East Caribbean Dollar', jaName: '東カリブドル', symbol: '\$'),
  'XDR': Currency(code: 'XDR', cnName: '特别提款权', enName: 'Special Drawing Rights', jaName: '特別引出権', symbol: 'SDR'),
  'XOF': Currency(code: 'XOF', cnName: '西非法郎', enName: 'West African CFA Franc', jaName: '西アフリカCFAフラン', symbol: 'CFA'),
  'XPF': Currency(code: 'XPF', cnName: '太平洋法郎', enName: 'CFP Franc', jaName: 'CFPフラン', symbol: '₣'),
  'YER': Currency(code: 'YER', cnName: '也门里亚尔', enName: 'Yemeni Rial', jaName: 'イエメンリアル', symbol: '﷼'),
  'ZAR': Currency(code: 'ZAR', cnName: '南非兰特', enName: 'South African Rand', jaName: '南アフリカランド', symbol: 'R'),
  'ZMW': Currency(code: 'ZMW', cnName: '赞比亚克瓦查', enName: 'Zambian Kwacha', jaName: 'ザンビアクワチャ', symbol: 'ZK'),
  'ZWL': Currency(code: 'ZWL', cnName: '津巴布韦元', enName: 'Zimbabwean Dollar', jaName: 'ジンバブエドル', symbol: 'Z\$'),
};

Currency currencyOf(String code) =>
    kCurrencyMeta[code] ?? Currency(code: code, cnName: code, symbol: code);

/// Orders currency [codes] with the common ones first (in the order they
/// appear in [kPopularCurrencies]), followed by the rest alphabetically.
///
/// Used by the rates list and the currency picker so frequently-used
/// currencies stay near the top while the full ~160-code set remains
/// reachable below.
List<String> sortByPopularity(Iterable<String> codes) {
  final rank = <String, int>{
    for (var i = 0; i < kPopularCurrencies.length; i++)
      kPopularCurrencies[i]: i,
  };
  final list = codes.toList();
  list.sort((a, b) {
    final ra = rank[a];
    final rb = rank[b];
    if (ra != null && rb != null) return ra.compareTo(rb);
    if (ra != null) return -1;
    if (rb != null) return 1;
    return a.compareTo(b);
  });
  return list;
}
